### ISSUE TITLE
So cute. Can I translate it into Chinese and share it with my students?

### ISSUE THREAD

**Issue by QuinceyWu** [icoxfog417/mlnote-note#3]
please QwQ

**Comment by icoxfog417** [comment]
Thank you for your interest 😸 . Because of this repository is licensed by [MIT](https://github.com/icoxfog417/mlnote-note/blob/main/LICENSE), you can translate and distribute to your students. The original [mlnote](https://github.com/chokkan/mlnote) is under CC BY-NC-ND 4.0 so that please taking care when you translate mlnote itself.

You can use the [PPT slides](https://github.com/icoxfog417/mlnote-note/blob/main/mlnote-slides.pptx) to translate.
